---
version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  labels:
    - dependabot
    - automerge
    - actions
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  labels:
    - dependabot
    - automerge
    - submodules
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  labels:
    - dependabot
    - automerge
    - python
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  labels:
    - dependabot
    - automerge
    - node
