---
version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  labels:
    - dependabot
    - automerge
    - gha
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - kornicameister
  labels:
    - dependabot
    - automerge
    - git
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  labels:
    - dependabot
    - automerge
    - pip
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  labels:
    - dependabot
    - automerge
    - npm
